export const ROLES = {
  CUSTOMER: 'CUSTOMER',
  STAFF: 'STAFF',
  ADMIN: 'ADMIN',
}

export const OPS_ROLES = [ROLES.STAFF, ROLES.ADMIN]

export const ORDER_STATUSES = [
  'PENDING',
  'CONFIRMED',
  'SHIPPED',
  'DELIVERED',
  'CANCELLED',
]

export const SHIPMENT_STATUSES = ['CREATED', 'IN_TRANSIT', 'DELIVERED']

export const BATCH_JOB_TYPES = [
  'IMPORT_PRODUCT_DATA',
  'GENERATE_DAILY_REPORTS',
  'AGGREGATE_SALES_DATA',
]
